syntax = "proto3";

package auth;

service AuthService {
  rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenResponse);
  rpc GetUser (GetUserRequest) returns (GetUserResponse);
}


message ValidateTokenRequest {
  string token = 1;
}
message ValidateTokenResponse {
  string userId    = 1;
  string role      = 2;
  string sessionId = 3;
  string jti       = 4;
}


message GetUserRequest {
  string userId = 1;
}
message GetUserResponse {
  string id          = 1;
  string email       = 2;
  string phoneNo     = 3;
  string role        = 4;
  string firstName   = 5;
  string middleName  = 6;
  string lastName    = 7;
  string address     = 8;
}